name: fluram
description: "Rick & Morty Fan App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  go_router: ^14.4.1
  flutter_launcher_icons: ^0.14.1
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  pretty_dio_logger: ^1.4.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.2
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2
  freezed: ^2.5.7
  json_serializable: ^6.8.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/app_icon/
    - assets/animations/


flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/app_icon/ic_launcher.jpg"
  min_sdk_android: 21