name: FluRaM on Web

on:
  push:
   branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    if: github.actor == 'dherediat97'
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
        - run: flutter clean
        - run: flutter pub get
        - run: flutter pub run build_runner build --delete-conflicting-outputs
        - uses: bluefireteam/flutter-gh-pages@v8
          with:
            baseHref: /FluRaM/
            targetBranch: gh-pages
            webRenderer: html
